export abstract class FontSize {
    static readonly text_xs = "text-xs"
    static readonly text_sm = "text-sm"
    static readonly text_base = "text-base"
    static readonly text_lg = "text-lg"
    static readonly text_xl = "text-xl"
    static readonly text_2xl = "text-2xl"
    static readonly text_3xl = "text-3xl"
    static readonly text_4xl = "text-4xl"
    static readonly text_5xl = "text-5xl"
    static readonly text_6xl = "text-6xl"
    static readonly text_7xl = "text-7xl"
    static readonly text_8xl = "text-8xl"
    static readonly text_9xl = "text-9xl"
}