export const Columns = {
    '1': 'columns-1',
    '2': 'columns-2',
    '3': 'columns-3',
    '4': 'columns-4',
    '5': 'columns-5',
    '6': 'columns-6',
    '7': 'columns-7',
    '8': 'columns-8',
    '9': 'columns-9',
    '10': 'columns-10',
    '11': 'columns-11',
    '12': 'columns-12',
    '3xs': 'columns-3xs',
    '2xs': 'columns-2xs',
    'xs': 'columns-xs',
    'sm': 'columns-sm',
    'md': 'columns-md',
    'lg': 'columns-lg',
    'xl': 'columns-xl',
    '2xl': 'columns-2xl',
    '3xl': 'columns-3xl',
    '4xl': 'columns-4xl',
    '5xl': 'columns-5xl',
    '6xl': 'columns-6xl',
    '7xl': 'columns-7xl',
} as const