export enum Display {
    block = 'block',
    inline_block = 'inline-block',
    inline = 'inline',
    flex = 'flex',
    inline_flex = 'inline-flex',
    table = 'table',
    inline_table = 'inline-table',
    table_caption = 'table-caption',
    table_cell = 'table-cell',
    table_column = 'table-column',
    table_column_group = 'table-column-group',
    table_footer_group = 'table-footer-group',
    table_header_group = 'table-header-group',
    table_row_group = 'table-row-group',
    table_row = 'table-row',
    flow_root = 'flow-root',
    grid = 'grid',
    inline_grid = 'inline-grid',
    contents = 'contents',
    list_item = 'list-item',
    hidden = 'hidden',
}