export const BoxShadow = {
    'shadow-sm': 'shadow-sm',
    'shadow': 'shadow',
    'shadow-md': 'shadow-md',
    'shadow-lg': 'shadow-lg',
    'shadow-xl': 'shadow-xl',
    'shadow-2xl': 'shadow-2xl',
    'shadow-inner': 'shadow-inner',
    'shadow-none': 'shadow-none',

    'hover:shadow-sm': 'hover:shadow-sm',
    'hover:shadow': 'hover:shadow',
    'hover:shadow-md': 'hover:shadow-md',
    'hover:shadow-lg': 'hover:shadow-lg',
    'hover:shadow-xl': 'hover:shadow-xl',
    'hover:shadow-2xl': 'hover:shadow-2xl',
    'hover:shadow-inner': 'hover:shadow-inner',
    'hover:shadow-none': 'hover:shadow-none',

    'focus:shadow-sm': 'focus:shadow-sm',
    'focus:shadow': 'focus:shadow',
    'focus:shadow-md': 'focus:shadow-md',
    'focus:shadow-lg': 'focus:shadow-lg',
    'focus:shadow-xl': 'focus:shadow-xl',
    'focus:shadow-2xl': 'focus:shadow-2xl',
    'focus:shadow-inner': 'focus:shadow-inner',
    'focus:shadow-none': 'focus:shadow-none',

    'active:shadow-sm': 'active:shadow-sm',
    'active:shadow': 'active:shadow',
    'active:shadow-md': 'active:shadow-md',
    'active:shadow-lg': 'active:shadow-lg',
    'active:shadow-xl': 'active:shadow-xl',
    'active:shadow-2xl': 'active:shadow-2xl',
    'active:shadow-inner': 'active:shadow-inner',
    'active:shadow-none': 'active:shadow-none'
} as const