export const BackgroundOpacity = {
    'bg-opacity-0': 'bg-opacity-0',
    'bg-opacity-5': 'bg-opacity-5',
    'bg-opacity-10': 'bg-opacity-10',
    'bg-opacity-15': 'bg-opacity-15',
    'bg-opacity-20': 'bg-opacity-20',
    'bg-opacity-25': 'bg-opacity-25',
    'bg-opacity-30': 'bg-opacity-30',
    'bg-opacity-35': 'bg-opacity-35',
    'bg-opacity-40': 'bg-opacity-40',
    'bg-opacity-45': 'bg-opacity-45',
    'bg-opacity-50': 'bg-opacity-50',
    'bg-opacity-55': 'bg-opacity-55',
    'bg-opacity-60': 'bg-opacity-60',
    'bg-opacity-65': 'bg-opacity-65',
    'bg-opacity-70': 'bg-opacity-70',
    'bg-opacity-75': 'bg-opacity-75',
    'bg-opacity-80': 'bg-opacity-80',
    'bg-opacity-85': 'bg-opacity-85',
    'bg-opacity-90': 'bg-opacity-90',
    'bg-opacity-95': 'bg-opacity-95',
    'bg-opacity-100': 'bg-opacity-100'
} as const
